version: '3.8'

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "3050:3050"
    expose:
      - "3050"
  
  frontend:
    stdin_open: true
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "5173:5173"
    expose:
      - "5173"
      
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
    expose:
      - "3000"